.PHONY : all clean

all : ex1 ex2 ex3 ex4 ex5

ex1 : ex1.c
	cc ex1.c -o ex1 -lpthread

ex2 : ex2.c
	cc ex2.c -o ex2 -lpthread

ex3 : ex3.c
	cc ex3.c -o ex3 -lpthread

ex4 : ex4.c
	cc ex4.c -o ex4 -lpthread

ex5 : ex5.c
	cc ex5.c -o ex5 -lpthread

clean :
	rm ex1 ex2 ex3 ex4 ex5
